// Domain objects
/**
 * @typedef {Object} SoundiizPlaylist
 * @property {string} id - The playlist ID.
 * @property {string} platform - The platform of the playlist.
 * @property {string} title - The title of the playlist.
 * @property {string} playlistLink - The link to the playlist.
 * @property {string} link - The link to the playlist.
 * @property {number} creationDate - The creation date of the playlist as a timestamp.
 * @property {string|null} description - The description of the playlist, if any.
 * @property {string} picture - The URL to the playlist picture.
 * @property {number} isMine - Indicates if the playlist is owned by the user.
 * @property {number} isPublic - Indicates if the playlist is public.
 * @property {number} nbTracks - The number of tracks in the playlist.
 * @property {string} statut - The status of the playlist.
 * @property {number} autoGenerated - Indicates if the playlist is auto-generated.
 * @property {string} creatorID - The ID of the playlist creator.
 * @property {string} creator - The name of the playlist creator.
 * @property {string} creatorLink - The link to the creator's profile.
 * @property {boolean} opened - Indicates if the playlist is opened.
 */

/**
 * @typedef {Object} SoundiizBatch
 * @property {number} id - The ID of the sync.
 * @property {keyof SoundiizPlatform} destination - The destination platform (e.g., 'applemusicapp').
 * @property {number} statut - The status code of the sync.
 * @property {EpochTimeStamp} createdDate - The creation date of the sync as a timestamp.
 * @property {EpochTimeStamp|null} startDate - The start date of the sync as a timestamp or null if not started.
 * @property {EpochTimeStamp|null} endDate - The end date of the sync as a timestamp or null if not ended.
 * @property {number} nbPlaylists - The number of playlists in the sync.
 * @property {number} nbAlbums - The number of albums in the sync.
 * @property {number} nbArtists - The number of artists in the sync.
 * @property {number} nbTracks - The number of tracks in the sync.
 * @property {boolean} isCanceled - Indicates whether the sync is canceled.
 */

// API Request Payloads
/**
 * @typedef {Object} SoundiizBatchTransferPayload
 * @property {string} dest - The destination platform.
 * @property {SoundiizPlaylist[]} playlists - An array of playlists.
 * @property {Object[]} albums - An array of albums.
 * @property {Object[]} artists - An array of artists.
 * @property {Object[]} tracks - An array of tracks.
 * @property {string} method - The method used.
 */

// API responses
/**
 * @typedef {Object} SoundiizSyncSuccessResponse
 * @property {boolean} data
 */

/**
 * @typedef {Object} SoundiizErrorResponse
 * @property {string} error
 * @property {number} error_code
 * @property {string} error_message
 */

/**
 * @typedef {Object} SoundiizPlaylistResponse
 * @property {SoundiizPlaylist[]} data
 */

/**
 * @typedef {Object} SoundiizBatchTransferResponse
 * @property {Object<'batch', SoundiizBatch>} data
 */